name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      is_main: ${{ steps.check_main.outputs.is_main }}
    
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          
      - name: Verify tag is on main
        id: check_main
        run: |
          if git branch -r --contains ${{ github.ref }} | grep -q "origin/main"; then
            echo "is_main=true" >> $GITHUB_OUTPUT
          else
            echo "is_main=false" >> $GITHUB_OUTPUT
          fi
          
      - name: Generate a changelog
        if: steps.check_main.outputs.is_main == 'true'
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          args: --latest --strip header
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}
          
      - name: Publish Release
        if: steps.check_main.outputs.is_main == 'true'
        uses: softprops/action-gh-release@v3
        with:
          body_path: CHANGELOG.md

  deploy:
    needs: release
    if: needs.release.outputs.is_main == 'true'
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      pages: write
      id-token: write
